# site settings
title: Shreyas
subtitle: Bapat
email: hello@shreyasb.com
description: A brief overview of my profile and what I do to earn and to feel good.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: B21 Beas Kund Hostel, IIT Mandi
city: Mandi
state: Himachal Pradesh
zip_code: 175005
country: India
phone: (+91) 9131-851-172

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/shreyasbapat
gitlab_url: https://gitlab.com/u/shreyasbapat
googleplus_url: 
instagram_url: https://instagram.com/shreyasbapat
linkedin_url: https://www.linkedin.com/in/shreyasbapat
pinterest_url:
slack_url:
twitter_url: https://twitter.com/astroshreyas

# build settings
markdown: kramdown

sass:
  style: compressed
